apiVersion: apps/v1
kind: Deployment
metadata:
  name: aricluster
  labels:
    app: aricluster
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: aricluster
  template:
    metadata:
      labels:
        app: aricluster
    spec:
      containers:
        - name: aricluster
          image: 462613583642.dkr.ecr.us-east-2.amazonaws.com/primuslearning:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080